/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData grapes = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData child_care = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData orange = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData tomato = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData strawberry = const IconData(0xe80b, fontFamily: _kFontFam);
}
